const catalogoProdutos = [
    {
        id :1,
        title: 'Adidas Tênis masculino Park St',
        price: 'R$349,80',
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',
        poster:['./img/TenisAdidas/mas/tenis1/adidasL.jpg', './img/TenisAdidas/mas/tenis1/adidasPar.jpg','./img/TenisAdidas/mas/tenis1/adidasT.jpg'],
        categories:'new',
        showHome: false,
        brand: "adidas",
        departament:"male"
    },
    {
        id :2,
        title: 'ADIDAS ORIGINALS Tênis Unissex Superstar - Branco',
        price: 'R$599,99',
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',
        poster:['./img/TenisAdidas/mas/tenis2/adidasPar.jpg','./img/TenisAdidas/mas/tenis2/adidasL.jpg','./img/TenisAdidas/mas/tenis2/adidasC.jpg','./img/TenisAdidas/mas/tenis2/adidas_exemplo.jpg'],
        categories:'new',
        showHome: true,
        brand: "adidas",
        departament:"male"
    },
    {
        id :3,
        title: 'Adidas Originals Tênis masculino Swift Essential',
        price: 'R$674,57',
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',
        poster:['./img/TenisAdidas/mas/tenis3/adidasL.jpg','./img/TenisAdidas/mas/tenis3/adidasC.jpg','./img/TenisAdidas/mas/tenis3/adidasF.jpg','./img/TenisAdidas/mas/tenis3/adidasPar.jpg'],
        categories:'new',
        showHome: true,
        brand: "adidas",
        departament:"male"
    },
    {
        id :4,
        title: ' Senseboost Go M Adidas - masculino',
        price: 'R$989,01',
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',
        poster:['./img/TenisAdidas/mas/tenis4/adidasPar.jpg','./img/TenisAdidas/mas/tenis4/adidasL.jpg','./img/TenisAdidas/mas/tenis4/adidasL-.jpg','./img/TenisAdidas/mas/tenis4/adidasS.jpg'],
        categories:'new',
        showHome: true,
        brand: "adidas",
        departament:"male"
    },
    {
        id :5,
        title: 'Adidas Originals Tênis masculino Seeley - Azul Marinho',
        price: 'R$394,09',
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',
        poster:['./img/TenisAdidas/mas/tenis5/adidasL.jpg','./img/TenisAdidas/mas/tenis5/adidasC.jpg','./img/TenisAdidas/mas/tenis5/adidasPar.jpg','./img/TenisAdidas/mas/tenis5/adidasT.jpg'],
        categories:'new',
        showHome: false,
        brand: "adidas",
        departament:"male"
    },
    {
        id :6,
        title: 'Tênis Masculino Alphaedge - Adidas.',
        price: 'R$599,99',
        poster:['./img/TenisAdidas/mas/tenis6/adidasPar.jpg','./img/TenisAdidas/mas/tenis6/adidasL.jpg','./img/TenisAdidas/mas/tenis6/adidasC.jpg','./img/TenisAdidas/mas/tenis6/adidasT.jpg'],
        categories:'new',
        showHome: false,
        brand: "adidas",
        departament:"male",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },
    {
        id :7,
        title: 'Tenis Adidas ORIGINALS Ozelia masculino',
        price: 'R$600.90',
        poster:['./img/TenisAdidas/mas/tenis8/adidasL.jpg','./img/TenisAdidas/mas/tenis7/adidasPar.jpg','./img/TenisAdidas/mas/tenis7/adidasC.jpg','./img/TenisAdidas/mas/tenis7/adidasT.jpg'],
        categories:'new',
        showHome: true,
        brand: "adidas",
        departament:"male",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },
    {
        id :8,
        title: 'Tenis Masculino Grand Court 2.0 - Branco',
        price: 'R$350,00',
        poster:['./img/TenisAdidas/mas/tenis7/adidasPar.jpg','./img/TenisAdidas/mas/tenis7/adidasL.jpg','./img/TenisAdidas/mas/tenis7/adidasC.jpg','./img/TenisAdidas/mas/tenis7/adidasT.jpg'],
        categories:'new',
        showHome: true,
        brand: "adidas",
        departament:"male",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },
    {
        id :9,
        title: 'Adidas Originals',
        price: 'R$599,99',
        poster:['./img/TenisAdidas/mas/tenis10/adidasL.jpg','./img/TenisAdidas/mas/tenis10/adidasF.jpg','./img/TenisAdidas/mas/tenis10/adidasC.jpg','./img/TenisAdidas/mas/tenis10/adidasT.jpg'],
        categories:'new',
        showHome: false,
        brand: "adidas",
        departament:"male",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },
    {
        id :10,
        title: 'ADIDAS ORIGINALS - Tênis Masculino Superstar - Vermelho ',
        price: 'R$359.00',
        poster:['./img/TenisAdidas/mas/tenis9/adidasPar.jpg','./img/TenisAdidas/mas/tenis9/adidasPar.jpg','./img/TenisAdidas/mas/tenis9/adidasC.jpg','./img/TenisAdidas/mas/tenis7/adidasF.jpg'],
        categories:'new',
        showHome: true,
        brand: "adidas",
        departament:"male",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },
    {
        id :11,
        title: 'Nike Court Vision',
        price: 'R$359.00',
        poster:['./img/TenisNike/mas/tenis1/nikeL.jpg','./img/TenisNike/mas/tenis1/nikeC.jpg','./img/TenisNike/mas/tenis1/nikePar.jpg','./img/TenisNike/mas/tenis1/nikeS.jpg'],
        categories:'new',
        showHome: true,
        brand: "nike",
        departament:"male",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },
    {
        id :12,
        title: 'Nike Blazer Mid  ',
        price: ' R$845,48',
        poster:['./img/TenisNike/mas/tenis3/nikePar.jpg','./img/TenisNike/mas/tenis3/nikeF.jpg','./img/TenisNike/mas/tenis3/nikeC.jpg','./img/TenisNike/mas/tenis3/nikeL.jpg'],
        categories:'new',
        showHome: true,
        brand: "nike",
        departament:"male",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },
    {
        id :13,
        title: 'Calçado para corrida NIKE Nike Air Zoom Pegasus',
        price: 'R$899.90',
        poster:['./img/TenisNike/mas/tenis2/nikeL.jpg','./img/TenisNike/mas/tenis2/nikeF.jpg','./img/TenisNike/mas/tenis2/nikeT.jpg','./img/TenisNike/mas/tenis2/nikeD.jpg'],
        categories:'new',
        showHome: false,
        brand: "nike",
        departament:"male",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },
    {
        id :14,
        title: 'NIKE Tênis Masculino Zoom Fly 5 ',
        price: 'R$1.299,99',
        poster:['./img/TenisNike/mas/tenis4/nikePar.jpg','./img/TenisNike/mas/tenis2/nikeF.jpg','./img/TenisNike/mas/tenis4/nikeC.jpg','./img/TenisNike/mas/tenis4/nikeL.jpg'],
        categories:'new',
        showHome: true,
        brand: "nike",
        departament:"male",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },

    {
        id :15,
        title: 'Tênis Nike Air Max',
        price: 'R$712,10',
        poster:['./img/TenisNike/mas/tenis5/nikeL.jpg','./img/TenisNike/mas/tenis5/nikeLl.jpg','./img/TenisNike/mas/tenis5/nikeC.jpg','./img/TenisNike/mas/tenis5/nikePar.jpg'],
        categories:'new',
        showHome: true,
        brand: "nike",
        departament:"male",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },

    {
        id :16,
        title: 'NIKE Tênis Masculino Venture Runner',
        price: 'R$450.00',
        poster:['./img/TenisNike/mas/tenis6/nikePar.jpg','./img/TenisNike/mas/tenis6/nikeF.jpg','./img/TenisNike/mas/tenis6/nikeC.jpg','./img/TenisNike/mas/tenis6/nikeL.jpg'],
        categories:'new',
        showHome: true,
        brand: "nike",
        departament:"male"
    },
   
    {
        id :16,
        title: 'Air Max Excee - Branco',
        price: 'R$519.99',
        poster:['./img/TenisNike/mas/tenis7/nikeL.jpg','./img/TenisNike/mas/tenis7/nikeLl.jpg','./img/TenisNike/mas/tenis7/nikePar.jpg','./img/TenisNike/mas/tenis7/nikeC.jpg'],
        categories:'new',
        showHome: false,
        brand: "nike",
        departament:"male",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },
    {
        id :77,
        title: 'Nike Precision 6 ',
        price: 'R$599.99',
        poster:['./img/TenisNike/mas/tenis9/nikePar.jpg','./img/TenisNike/mas/tenis9/nikeL.jpg','./img/TenisNike/mas/tenis9/nikeC.jpg','./img/TenisNike/mas/tenis9/nikeT.jpg'],
        categories:'new',
        showHome: false,
        brand: "nike",
        departament:"male",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },

    {
        id :88,
        title: 'Nike Tênis masculino - Cerejeira Vermelho',
        price: 'R$1.805,98',
        poster:['./img/TenisNike/mas/tenis10/nikeL.jpg','./img/TenisNike/mas/tenis10/nikeF.jpg','./img/TenisNike/mas/tenis10/nikeC.jpg','./img/TenisNike/mas/tenis10/nikeT.jpg'],
        categories:'new',
        showHome: true,
        brand: "nike",
        departament:"male",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },
    {
        id :99,
        title: 'Nike Tênis masculino',
        price: 'R$755.00',
        poster:['./img/TenisNike/mas/tenis8/nikeL.jpg','./img/TenisNike/mas/tenis8/nikeC.jpg','./img/TenisNike/mas/tenis8/nikeS.jpg','./img/TenisNike/mas/tenis8/nikeT.jpg'],
        categories:'new',
        showHome: true,
        brand: "nike",
        departament:"male",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },
    {
        id :17,
        title: 'Adidas Court Feminino',
        price: 'R$350,00',
        poster:['./img/TenisAdidas/fem/tenis2/adidasL.jpg','./img/TenisAdidas/fem/tenis2/adidasC.jpg','./img/TenisAdidas/fem/tenis2/adidasPar.jpg','./img/TenisAdidas/fem/tenis2/adidasT.jpg'],
        categories:'new',
        showHome: false,
        brand: "adidas",
        departament:"female",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },
    {
        id :18,
        title: 'Tênis Adidas  Grand Court 2.0 ',
        price: 'R$350.00',
        poster:['./img/TenisAdidas/fem/tenis1/adidasPar.jpg','./img/TenisAdidas/fem/tenis1/adidasC.jpg','./img/TenisAdidas/fem/tenis1/adidasL.jpg','./img/TenisAdidas/fem/tenis1/adidasT.jpg'],
        categories:'new',
        showHome: false,
        brand: "adidas",
        departament:"female",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },
    {
        id :19,
        title: 'Tênis Adidas ORIGINALS Superstar ',
        price: 'R$766,69',
        poster:['./img/TenisAdidas/fem/tenis3/adidasL.jpg','./img/TenisAdidas/fem/tenis3/adidasC.jpg','./img/TenisAdidas/fem/tenis3/adidasS.jpg','./img/TenisAdidas/fem/tenis3/adidasT.jpg'],
        categories:'new',
        showHome: false,
        brand: "adidas",
        departament:"female",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },
    {
       
        id :20,
        title: 'Adidas Feminino ',
        price: 'R$450.90',
        poster:['./img/TenisAdidas/fem/tenis10/adidasPar.jpg','./img/TenisAdidas/fem/tenis10/adidasL.jpg','./img/TenisAdidas/fem/tenis10/adidasF.jpg','./img/TenisAdidas/fem/tenis10/adidasT.jpg'],
        categories:'new',
        showHome: false,
        brand: "adidas",
        departament:"female",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },
    {
        id :21,
        title: 'Adidas Court',
        price: 'R$300.00',
        poster:['./img/TenisAdidas/fem/tenis4/adidasPar.jpg','./img/TenisAdidas/fem/tenis4/adidasC.jpg','./img/TenisAdidas/fem/tenis4/adidas_exemplo.jpg','./img/TenisAdidas/fem/tenis4/adidasL.jpg'],
        categories:'new',
        showHome: false,
        brand: "adidas",
        departament:"female",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },
    {
        id :22,
        title: 'Adidas Sport',
        price: 'R$259.00',
        poster:['./img/TenisAdidas/fem/tenis5/adidasPar.jpg','./img/TenisAdidas/fem/tenis5/adidasC.jpg','./img/TenisAdidas/fem/tenis5/adidasL.jpg','./img/TenisAdidas/fem/tenis5/adidasT.jpg'],
        categories:'new',
        showHome: false,
        brand: "adidas",
        departament:"female",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },
    {
        id :23,
        title: 'Adidas Streifen',
        price: 'R$399.00',
        poster:['./img/TenisAdidas/fem/tenis6/adidasL.jpg','./img/TenisAdidas/fem/tenis6/adidasC.jpg','./img/TenisAdidas/fem/tenis6/adidasF.jpg','./img/TenisAdidas/fem/tenis6/adidasT.jpg'],
        categories:'new',
        showHome: false,
        brand: "adidas",
        departament:"female",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },
    {
        id :24,
        title: 'Adidas Forum Low',
        price: 'R$450.99',
        poster:['./img/TenisAdidas/fem/tenis7/adidasL.jpg','./img/TenisAdidas/fem/tenis3/adidasC.jpg','./img/TenisAdidas/fem/tenis3/adidasS.jpg','./img/TenisAdidas/fem/tenis3/adidasT.jpg'],
        categories:'new',
        showHome: false,
        brand: "adidas",
        departament:"female",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',


    },
    {
        id :25,
        title: 'Adidas Feminino',
        price: 'R$300.00',
        poster:['./img/TenisAdidas/fem/tenis8/adidasPar.jpg','./img/TenisAdidas/fem/tenis8/adidasC.jpg','./img/TenisAdidas/fem/tenis8/adidasF.jpg','./img/TenisAdidas/fem/tenis8/adidasL.jpg'],
        categories:'new',
        showHome: false,
        brand: "adidas",
        departament:"female",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },
    {
        id :26,
        title: 'Adidas Superstar Feminino',
        price: 'R$389.99',
        poster:['./img/TenisAdidas/fem/tenis9/adidasL.jpg','./img/TenisAdidas/fem/tenis9/adidasPar.jpg','./img/TenisAdidas/fem/tenis9/adidasF.jpg','./img/TenisAdidas/fem/tenis9/adidasT.jpg'],
        categories:'new',
        showHome: false,
        brand: "adidas",
        departament:"female",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },
    
    {
        id :28,
        title: ' NIKE  Air Max Exosense feminino',
        price: 'R$915,60',
        poster:['./img/TenisNike/fem/tenis1/nikeL.jpg','./img/TenisNike/fem/tenis1/nikeF.jpg','./img/TenisNike/fem/tenis1/nikeS.jpg','./img/TenisNike/fem/tenis1/nikeT.jpg'],
        categories:'new',
        showHome: false,
        brand: "nike",
        departament:"female",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },
    {
        id :29,
        title: 'Tênis Feminino Metcon 9 - Preto',
        price: 'R$1.199,99',
        poster:['./img/TenisNike/fem/tenis2/nikePar.jpg','./img/TenisNike/fem/tenis2/nikeL.jpg','./img/TenisNike/fem/tenis2/nikeC.jpg','./img/TenisNike/fem/tenis2/nike_exemplo.jpg'],
        categories:'new',
        showHome: false,
        brand: "nike",
        departament:"female",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },
    {
        id :30,
        title: 'NIKE  Revolution 6 Next Nature',
        price: 'R$316,18 ',
        poster:['./img/TenisNike/fem/tenis3/nikeL.jpg','./img/TenisNike/fem/tenis3/nikePar.jpg','./img/TenisNike/fem/tenis3/nikeC.jpg','./img/TenisNike/fem/tenis3/nikeT.jpg'],
        categories:'new',
        showHome: false,
        brand: "nike",
        departament:"female",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },
    {
        id :31,
        title: 'NIKE  Air Max Intrlk Lite',
        price: 'R$1.310,60',
        poster:['./img/TenisNike/fem/tenis4/nikePar.jpg','./img/TenisNike/fem/tenis4/nikeL.jpg','./img/TenisNike/fem/tenis4/nikeC.jpg','./img/TenisNike/fem/tenis4/nikeT.jpg'],
        categories:'new',
        showHome: false,
        brand: "nike",
        departament:"female",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },
    {
        id :32,
        title: ' Nike React Pegasus Trail 4 Gtx - Cinza',
        price: 'R$880,90',
        poster:['./img/TenisNike/fem/tenis5/nikePar.jpg','./img/TenisNike/fem/tenis5/nikeL.jpg','./img/TenisNike/fem/tenis5/nikeC.jpg','./img/TenisNike/fem/tenis5/nikeS.jpg'],
        categories:'new',
        showHome: false,
        brand: "nike",
        departament:"female",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },
    {
        id :33,
        title: 'Nike Tênis feminino WMNS Renew',
        price: 'R$342,03',
        poster:['./img/TenisNike/fem/tenis6/nikeF.jpg','./img/TenisNike/fem/tenis6/nikeL.jpg','./img/TenisNike/fem/tenis6/nikeT.jpg'],
        categories:'new',
        showHome: false,
        brand: "nike",
        departament:"female",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',

    },
    {
        id :37,
        title: 'Nike Renew In-season',
        price: 'R$871,21 ',
        poster:['./img/TenisNike/fem/tenis7/nikePar.jpg','./img/TenisNike/fem/tenis7/nikeL.jpg','./img/TenisNike/fem/tenis7/nikeF.jpg','./img/TenisNike/fem/tenis7/nikeS.jpg'],
        categories:'new',
        showHome: false,
        brand: "nike",
        departament:"female",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',


    },
    {
        id :34,
        title: 'NIKE  Air Max Intrlk Lite',
        price: 'R$1.410,38 ',
        poster:['./img/TenisNike/fem/tenis8/nikePar.jpg','./img/TenisNike/fem/tenis8/nikeL.jpg','./img/TenisNike/fem/tenis8/nikeF.jpg','./img/TenisNike/fem/tenis7/nikeC.jpg'],
        categories:'new',
        showHome: false,
        brand: "nike",
        departament:"female",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',


    },
    {
        id :35,
        title: 'NIKE Blazer feminino',
        price: 'R$967,66 ',
        poster:['./img/TenisNike/fem/tenis9/nikeL.jpg','./img/TenisNike/fem/tenis9/nikeH.jpg','./img/TenisNike/fem/tenis9/nikeF.jpg','./img/TenisNike/fem/tenis9/nikeT.jpg'],
        categories:'new',
        showHome: false,
        brand: "nike",
        departament:"female",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',


    },
    {
        id :36,
        title: 'NIKE Air Max Intrlk Lite',
        price: 'R$1.007,92 ',
        poster:['./img/TenisNike/fem/tenis10/nikePar.jpg','./img/TenisNike/fem/tenis10/nikeL.jpg','./img/TenisNike/fem/tenis10/nikeF.jpg','./img/TenisNike/fem/tenis10/nikeT.jpg'],
        categories:'new',
        showHome: false,
        brand: "nike",
        departament:"female",
        description:'O tênis é uma fusão de conforto e estilo, projetado para se adaptar ao seu estilo de vida dinâmico. Com uma combinação de design contemporâneo e desempenho excepcional, este calçado oferece um ajuste personalizado, garantindo conforto durante todo o dia. Construído com materiais de alta qualidade, apresenta durabilidade aprimorada, tornando-o ideal para diversas atividades, desde exercícios físicos até looks casuais. Seja para uma caminhada na cidade ou para compor seu visual diário, sendo uma escolha versátil que eleva seu estilo enquanto prioriza o conforto e a durabilidade.',


    },
]